[package]
name = "aya-btf-map"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main" }
aya-btf-map-macros = { path = "../aya-btf-map-macros" }
